#
# DO NOT EDIT THIS FILE!
# This file is generated by `scargo update`.
#

from conan import ConanFile
from conan.tools.cmake import CMake, cmake_layout
from conan.tools.files import copy, get
from conan.tools.scm import Git


class Example_projectConan(ConanFile):  # type: ignore[misc, no-any-unimported]
    name = "example_project"
    version = "0.1.0"
    license = "MIT"
    description = "Project description."
    settings = "os", "compiler", "build_type", "arch"
    url = "www.hello-world.com"
    generators = "CMakeToolchain", "CMakeDeps"
    exports_sources = ["src/*", "CMakeLists.txt", "include/*", "config/*"]

    def source(self) -> None:
        pass

    def layout(self) -> None:
        cmake_layout(self)

    def build(self) -> None:
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self) -> None:
        copy("*.bin")
        copy("*.elf")
