hide footbox

autoactivate on

hide unlinked

actor user
participant scargo #Application
participant sc_new #Application
participant sc_update #Application
participant sc_build #Application
participant conan #Implementation
participant cmake #Implementation
participant esp_idf #Implementation
participant "my_project_1" as storage  << (S,#ADD1B2) local storage >> #Physical
participant "package repository" as pkg_repo #Strategy
