WORKDIR /opt/

{% if project.is_stm32() %}
{% set additional_tools = 'stlink-tools' %}
{% else %}
{% set additional_tools = '' %}
{% endif %}

RUN apt-get update -q -y && \
    apt-get install -y --no-install-recommends curl wget openocd gdb-multiarch {{ additional_tools }} && \
    rm -rf /var/lib/apt/lists/*

# pull the gcc-arm-none-eabi tarball, add path to tar file
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 && \
    tar -xvf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 && \
    rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 && \
    mv gcc-arm-none-eabi-10.3-2021.10 gcc-arm-none-eabi

# Set up the compiler path
ENV PATH $PATH:/opt/gcc-arm-none-eabi/bin

ENV LC_ALL=C
