RUN apt-get update && \
    apt-get install -y software-properties-common && \
    rm -rf /var/lib/apt/lists/*

RUN add-apt-repository --remove ppa:team-gcc-arm-embedded/ppa

RUN apt-get update -q -y && \
    apt-get install -y --no-install-recommends curl wget openocd gdb-multiarch gcc-arm-none-eabi && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
    rm -rf /var/lib/apt/lists/*

ENV LC_ALL=C
