RUN  apt -y install flex bison gperf python3-setuptools ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

ARG ESPRESSIF_IDF_TAG="v4.4.3"
ARG ESPRESSIF_IDF_VERSION="${ESPRESSIF_IDF_TAG}"
ARG ESPRESSIF_IDF_PATH="/opt/esp-idf"
ARG ESPRESSIF_IDF_REPO_URL="https://github.com/espressif/esp-idf.git"
ARG ESPRESSIF_TOOLS_PATH="/root/.espressif"
ARG RUN_CLANG_TIDY_SCRIPT_URL="https://raw.githubusercontent.com/llvm/llvm-project/llvmorg-16.0.0/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py"
ENV  IDF_TOOLS_PATH ${ESPRESSIF_IDF_PATH}
ENV  IDF_PATH ${ESPRESSIF_IDF_PATH}

WORKDIR /opt

RUN umask 0002 && git clone --single-branch --branch ${ESPRESSIF_IDF_VERSION} --recursive ${ESPRESSIF_IDF_REPO_URL} ${ESPRESSIF_IDF_PATH}
RUN umask 0002 && ${ESPRESSIF_IDF_PATH}/install.sh
RUN umask 0002 && ${ESPRESSIF_IDF_PATH}/tools/idf_tools.py install xtensa-clang

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && \
    apt-get update && \
    apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg && \
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null && \
    AZ_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    tee /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update && \
    apt-get install azure-cli

ENV LC_ALL=C

RUN umask 0002 && mkdir /opt/esp/ && echo '#!/usr/bin/env bash\n\
\n\
set -e\n\
\n\
. $IDF_PATH/export.sh\n\
\n\
exec "$@"' >  /opt/esp/entrypoint.sh && chmod 775 /opt/esp/entrypoint.sh

RUN umask 0002 && /opt/esp-idf/python_env/idf4.4_py3.8_env/bin/pip install pyclang
RUN umask 0002 &&  curl -o /usr/bin/run-clang-tidy.py  ${RUN_CLANG_TIDY_SCRIPT_URL} && \
chmod 775 /usr/bin/run-clang-tidy.py

# Install QEMU
ARG QEMU_VER=esp-develop-20220919
ARG QEMU_DIST=qemu-${QEMU_VER}.tar.bz2
ARG QEMU_SHA256=f6565d3f0d1e463a63a7f81aec94cce62df662bd42fc7606de4b4418ed55f870
RUN : \
  && wget --no-verbose https://github.com/espressif/qemu/releases/download/${QEMU_VER}/${QEMU_DIST} \
  && echo "${QEMU_SHA256} *${QEMU_DIST}" | sha256sum --check --strict - \
  && tar -xf ${QEMU_DIST} -C /opt \
  && rm ${QEMU_DIST} \
  && :
ENV PATH=/opt/qemu/bin:${PATH}
