name: pull request ci
on:
  pull_request:
    branches: 
      - develop
      - main
      - 'releases/**'
      - 'env/test'
      - 'bugfix/ILAB-2273'

jobs:
  call-workflow:
    uses: ./.github/workflows/workflow-common.yml